# Generated by Django 5.2.17 on 2026-09-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('excerpt', models.TextField(max_length=400)),
                ('content', models.TextField(help_text='Plain text or safe HTML content.')),
                ('category', models.CharField(default='SEO', max_length=80)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags.', max_length=300)),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/')),
                ('author', models.CharField(default='Chandan Kumar Paswan', max_length=120)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('og_image', models.ImageField(blank=True, upload_to='blog/og/')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
